// 별빛 사주 — Star Archetype Catalog (2026-05).
// 16개 brand archetype. selector가 점수로 1개 선택.

import type { StarArchetype } from './starArchetypeTypes';

export const STAR_ARCHETYPE_CATALOG: StarArchetype[] = [
  {
    id: 'calm-victor',
    title: '차분한 얼굴로 승부를 보는 별',
    subtitle: '겉은 평온하지만, 결정적 순간에는 자기 기준으로 움직이는 사람',
    keywords: ['조용한 승부심', '기준선', '결단력', '버팀', '책임'],
    triggerSignals: ['양인', '괴강', '강한 비겁', '강한 일간', '자기 기준', '위기 대응력', '결단력'],
    avoidSignals: ['유연함 중심', '감성형 중심', '조화형 중심', '수용성 중심'],
    shortDescription: '겉으로는 조용하고 안정적으로 보이지만, 안쪽에는 쉽게 물러서지 않는 승부심이 있습니다. 남들이 우왕좌왕할 때 오히려 기준을 세우고, 흐트러진 상황을 정리하려는 힘이 올라오는 별입니다.',
    brightSide: '결정이 미뤄지고 책임이 흐려진 상황에서 중심을 잡아야 할 때 빛납니다.',
    shadowSide: '모두가 괜찮은 줄 알고 책임을 맡길 때, 혼자 너무 오래 버티며 지칠 수 있습니다.',
    growthDirection: '혼자 승부를 보는 힘을 기준과 역할 분담으로 바꿀 때 더 크게 빛납니다.',
    evidence: [],
  },
  {
    id: 'quiet-commander',
    title: '조용히 판을 정리하는 별',
    subtitle: '흐트러진 상황에서 기준을 세우고 중심을 잡는 사람',
    keywords: ['정리력', '기준', '책임', '중심', '판 정리'],
    triggerSignals: ['무토', '강한 토', '책임', '운영 개선', '정리력', '괴강', '양인'],
    shortDescription: '겉으로는 차분해 보여도, 일이 흐트러지는 순간 기준을 세우고 중심을 잡는 사람입니다. 남들이 우왕좌왕할 때 오히려 "그럼 내가 정리해야지" 쪽으로 힘이 모이는 별입니다.',
    brightSide: '복잡한 상황을 정리하고, 책임과 권한이 분명한 자리에서 실력이 드러날 때 빛납니다.',
    shadowSide: '모두가 당신을 괜찮은 사람으로 보고, 책임이 자연스럽게 몰릴 때 지칠 수 있습니다.',
    growthDirection: '정리하는 힘을 혼자 쓰지 않고, 사람들과 역할을 나눌 때 더 크게 빛납니다.',
    evidence: [],
  },
  {
    id: 'unfading-standard',
    title: '쉽게 꺼지지 않는 기준의 별',
    subtitle: '자기 기준을 오래 지키며 신뢰를 쌓는 사람',
    keywords: ['기준', '신뢰', '버팀', '원칙', '지속력'],
    triggerSignals: ['자기 기준', '정관', '강한 토', '괴강', '버티는 힘'],
    shortDescription: '쉽게 흔들리지 않는 기준을 가지고, 시간이 걸려도 자기 방식으로 신뢰를 쌓아가는 별입니다.',
    brightSide: '기준과 책임이 필요한 자리에서 꾸준히 신뢰를 쌓을 때 빛납니다.',
    shadowSide: '기준이 너무 높아 시작이 늦어지거나, 혼자만 엄격해질 때 지칠 수 있습니다.',
    growthDirection: '기준을 지키되, 완벽해지기 전에도 작은 결과물을 꺼낼 때 더 밝아집니다.',
    evidence: [],
  },
  {
    id: 'result-maker',
    title: '말보다 결과로 증명하는 별',
    subtitle: '설명보다 결과물로 신뢰를 만드는 사람',
    keywords: ['결과물', '신뢰', '책임', '성과', '증명'],
    triggerSignals: ['정관', '책임', '결과물', '신뢰', '성과', '꾸준함'],
    shortDescription: '말로 크게 자신을 드러내기보다, 결과물과 책임감으로 신뢰를 쌓아가는 별입니다.',
    brightSide: '맡은 일을 끝까지 정리하고, 결과물로 평가받는 자리에서 빛납니다.',
    shadowSide: '과정에서 힘든 점을 말하지 않고 혼자 감당할 때 지칠 수 있습니다.',
    growthDirection: '결과만 보여주려 하기보다, 중간 과정과 필요한 도움을 함께 공유할 때 더 안정적으로 빛납니다.',
    evidence: [],
  },
  {
    id: 'idea-maker',
    title: '생각을 결과물로 바꾸는 별',
    subtitle: '머릿속 아이디어를 밖으로 꺼낼 때 빛나는 사람',
    keywords: ['표현', '결과물', '콘텐츠', '아이디어', '생산성'],
    triggerSignals: ['식신', '상관', '식상 강함', '표현성', '콘텐츠', '창작', '기획'],
    shortDescription: '머릿속에만 있을 때보다, 말·글·콘텐츠·작품·서비스처럼 밖으로 꺼낼 때 빛이 강해지는 별입니다.',
    brightSide: '아이디어를 실제 결과물로 만들고 사람들에게 보여줄 때 빛납니다.',
    shadowSide: '완벽하게 준비될 때까지 계속 미루면 기회가 늦어질 수 있습니다.',
    growthDirection: '완벽한 결과물보다 작은 공개와 반복 개선을 선택할 때 더 밝아집니다.',
    evidence: [],
  },
  {
    id: 'value-catcher',
    title: '기회를 현실로 바꾸는 별',
    subtitle: '흐름 속에서 쓸모와 가치를 찾아내는 사람',
    keywords: ['기회', '현실감', '자원', '수익화', '감각'],
    triggerSignals: ['재성', '편재', '정재', '현실감', '자원 관리', '수익화'],
    shortDescription: '사람들이 그냥 지나치는 흐름 속에서 쓸모와 가치를 찾아내는 감각이 있는 별입니다.',
    brightSide: '사람, 자원, 기회를 현실적인 결과로 연결할 때 빛납니다.',
    shadowSide: '가능성을 너무 많이 보다가 에너지가 분산될 때 지칠 수 있습니다.',
    growthDirection: '기회를 모두 잡으려 하기보다, 검증 가능한 작은 구조로 바꿀 때 더 안정적으로 빛납니다.',
    evidence: [],
  },
  {
    id: 'trust-builder',
    title: '책임이 커질수록 빛나는 별',
    subtitle: '무게 있는 역할에서 신뢰를 쌓는 사람',
    keywords: ['책임', '역할', '신뢰', '직함', '기준'],
    triggerSignals: ['정관', '편관', '관성 강함', '사회적 책임', '직함', '조직'],
    shortDescription: '가벼운 역할보다, 기준과 책임이 분명한 자리에서 더 강해지는 별입니다.',
    brightSide: '역할과 권한이 분명한 자리에서 신뢰를 결과로 만들 때 빛납니다.',
    shadowSide: '책임은 많은데 권한은 적은 환경에서는 쉽게 지칠 수 있습니다.',
    growthDirection: '책임을 맡기 전 권한과 범위를 분명히 할 때 더 안정적으로 빛납니다.',
    evidence: [],
  },
  {
    id: 'deep-learner',
    title: '깊이 쌓아 오래 빛나는 별',
    subtitle: '천천히 쌓은 깊이로 오래 가는 사람',
    keywords: ['깊이', '학습', '자격', '축적', '전문성'],
    triggerSignals: ['인성', '정인', '편인', '학습', '자격', '문서', '전문성'],
    shortDescription: '빠르게 치고 나가는 것보다, 충분히 이해하고 자기 것으로 만든 뒤 오래 가는 힘이 있는 별입니다.',
    brightSide: '하나를 깊게 쌓아 신뢰와 전문성으로 바꿀 때 빛납니다.',
    shadowSide: '생각은 충분히 했지만 밖으로 꺼내지 못하고 계속 준비만 할 때 지칠 수 있습니다.',
    growthDirection: '배운 것을 문서, 포트폴리오, 콘텐츠, 자격처럼 확인 가능한 형태로 남길 때 더 밝아집니다.',
    evidence: [],
  },
  {
    id: 'possibility-grower',
    title: '가능성을 키우는 별',
    subtitle: '작은 가능성을 발견하고 성장시키는 사람',
    keywords: ['성장', '방향', '기획', '확장', '가능성'],
    triggerSignals: ['목 기운', '성장', '기획', '확장', '교육', '새로운 시작'],
    shortDescription: '지금 완성된 것보다, 앞으로 자랄 수 있는 방향을 먼저 보는 별입니다.',
    brightSide: '작은 가능성을 발견하고 꾸준히 키워갈 때 빛납니다.',
    shadowSide: '방향만 많이 보고 실제 뿌리를 내리지 못할 때 지칠 수 있습니다.',
    growthDirection: '새로운 가능성을 현실적인 계획과 루틴으로 연결할 때 더 밝아집니다.',
    evidence: [],
  },
  {
    id: 'spark-maker',
    title: '꺼진 판에 불을 붙이는 별',
    subtitle: '멈춘 흐름에 에너지를 불어넣는 사람',
    keywords: ['에너지', '표현', '확산', '존재감', '몰입'],
    triggerSignals: ['화 기운', '표현', '존재감', '열정', '확산', '주목'],
    shortDescription: '가라앉은 분위기나 멈춘 흐름에 에너지를 불어넣는 힘이 있는 별입니다.',
    brightSide: '사람들의 시선을 모으고, 무언가를 시작하게 만드는 순간에 빛납니다.',
    shadowSide: '너무 오래 과열되거나 감정 소모가 커질 때 지칠 수 있습니다.',
    growthDirection: '뜨겁게 몰입하되, 회복 리듬을 함께 만들 때 더 오래 빛납니다.',
    evidence: [],
  },
  {
    id: 'sharp-standard',
    title: '흐릿한 것을 선명하게 자르는 별',
    subtitle: '애매한 상황에 기준선을 세우는 사람',
    keywords: ['판단', '절제', '완성도', '기준선', '정리'],
    triggerSignals: ['금 기운', '판단력', '절제', '완성도', '정리', '선 긋기'],
    shortDescription: '애매한 상황을 오래 두기보다, 기준을 세우고 필요한 것과 아닌 것을 구분하려는 힘이 있는 별입니다.',
    brightSide: '정리되지 않은 판에서 판단력과 완성도가 필요할 때 빛납니다.',
    shadowSide: '기준이 너무 날카로워져 스스로와 타인에게 엄격해질 때 지칠 수 있습니다.',
    growthDirection: '정확함을 유지하되, 사람의 속도까지 함께 고려할 때 더 부드럽게 빛납니다.',
    evidence: [],
  },
  {
    id: 'flow-reader',
    title: '고요히 판을 읽는 별',
    subtitle: '상황의 흐름과 사람의 마음을 먼저 읽는 사람',
    keywords: ['관찰', '흐름', '깊이', '직감', '정보'],
    triggerSignals: ['수 기운', '관찰력', '정보', '생각', '흐름', '유연함'],
    shortDescription: '겉으로 바로 움직이기보다, 상황의 흐름과 사람의 마음을 먼저 읽으려는 힘이 있는 별입니다.',
    brightSide: '충분히 관찰하고 흐름을 잡은 뒤 움직일 때 깊게 빛납니다.',
    shadowSide: '생각이 너무 많아지고 결정을 오래 미룰 때 지칠 수 있습니다.',
    growthDirection: '흐름을 읽은 뒤 작은 행동으로 연결할 때 더 선명하게 빛납니다.',
    evidence: [],
  },
  {
    id: 'memorable-aura',
    title: '분위기로 기억되는 별',
    subtitle: '시간이 지나도 인상이 남는 사람',
    keywords: ['분위기', '매력', '인상', '시선', '기억'],
    triggerSignals: ['도화', '홍염', '매력', '분위기', '표현성', '사람들의 시선'],
    shortDescription: '눈에 띄려고 애쓰지 않아도, 사람들에게 묘하게 인상이 남는 결이 있는 별입니다.',
    brightSide: '화려하게 드러내기보다, 자연스러운 분위기로 오래 기억될 때 빛납니다.',
    shadowSide: '시선과 기대를 너무 의식하면 본래의 매력이 흐려질 수 있습니다.',
    growthDirection: '보여주려는 힘보다 자연스럽게 드러나는 결을 믿을 때 더 매력적으로 빛납니다.',
    evidence: [],
  },
  {
    id: 'moving-opener',
    title: '움직일수록 길이 열리는 별',
    subtitle: '새로운 환경에서 가능성이 살아나는 사람',
    keywords: ['이동', '변화', '확장', '외부 활동', '새 판'],
    triggerSignals: ['역마', '이동', '변화', '외부 활동', '환경 변화', '확장'],
    shortDescription: '한곳에 오래 묶여 있을 때보다, 새로운 사람·장소·일을 만나며 가능성이 열리는 별입니다.',
    brightSide: '움직이며 새 흐름을 만날 때 빛납니다.',
    shadowSide: '한곳에 너무 오래 묶이거나 변화가 막힐 때 답답함이 커질 수 있습니다.',
    growthDirection: '변화를 피하기보다, 이동과 확장을 계획적으로 사용할 때 더 밝아집니다.',
    evidence: [],
  },
  {
    id: 'deep-world',
    title: '혼자 있을 때 더 깊어지는 별',
    subtitle: '고요한 시간 속에서 자기 세계가 깊어지는 사람',
    keywords: ['몰입', '깊이', '고독', '예술성', '자기 세계'],
    triggerSignals: ['화개', '고독', '몰입', '예술성', '철학성', '전문성'],
    shortDescription: '사람들 사이에서만 빛나는 타입이라기보다, 혼자만의 시간 속에서 생각과 감각이 깊어지는 별입니다.',
    brightSide: '혼자만의 시간을 자기 세계와 전문성으로 바꿀 때 빛납니다.',
    shadowSide: '고립이 길어져 사람과의 연결이 끊길 때 지칠 수 있습니다.',
    growthDirection: '고요한 몰입을 결과물이나 표현으로 연결할 때 더 특별해집니다.',
    evidence: [],
  },
  {
    id: 'help-through-people',
    title: '사람을 통해 길이 열리는 별',
    subtitle: '좋은 인연을 알아보고 연결할 때 빛나는 사람',
    keywords: ['인연', '도움', '연결', '귀인', '기회'],
    triggerSignals: ['천을귀인', '귀인', '인연', '도움', '좋은 조력자'],
    shortDescription: '혼자 힘으로만 가는 사주라기보다, 중요한 순간에 사람과 인연을 통해 길이 열릴 수 있는 별입니다.',
    brightSide: '좋은 인연을 알아보고 도움을 기회로 연결할 때 빛납니다.',
    shadowSide: '도움을 약점으로 여기고 혼자만 해결하려 할 때 기회를 놓칠 수 있습니다.',
    growthDirection: '혼자 해내는 힘과 좋은 인연을 활용하는 지혜를 함께 쓸 때 더 밝아집니다.',
    evidence: [],
  },
];

// ============================================================
// Fallback — 모든 점수가 너무 낮을 때
// ============================================================
export const STAR_ARCHETYPE_FALLBACK: StarArchetype = {
  id: 'own-pace',
  title: '자기만의 속도로 빛나는 별',
  subtitle: '자기 리듬으로 꾸준히 쌓아가는 사람',
  keywords: ['자기 결', '리듬', '꾸준함', '균형', '결'],
  triggerSignals: [],
  shortDescription: '빠르게 드러나는 빛보다, 자기 리듬을 찾고 꾸준히 쌓아갈 때 더 선명해지는 별입니다. 아직 한 가지 이름으로 단정하기보다, 당신만의 결을 차분히 만들어가는 흐름이 강합니다.',
  brightSide: '서두르지 않고 자기 속도를 지킬 때 빛납니다.',
  shadowSide: '주변과 비교하며 조급해질 때 흐려질 수 있습니다.',
  growthDirection: '비교 대신 어제의 자기와 견주며 한 걸음씩 갈 때 더 밝아집니다.',
  evidence: [],
};

export function findArchetypeById(id: string): StarArchetype | undefined {
  return STAR_ARCHETYPE_CATALOG.find(a => a.id === id);
}
