// 관계 아키타입 카탈로그 — 13개.
// GPT가 임의로 관계 이름을 만들지 못하게 코드가 후보를 결정한다.
// 재미 있는 비유는 허용하되 반드시 현실적 의미를 함께 갖는다.

import type { ArchetypeCatalogEntry } from '../compatibilityTypes';

export const RELATIONSHIP_ARCHETYPE_CATALOG: ArchetypeCatalogEntry[] = [
  {
    id: 'magnetic-pull',
    title: '아무리 밀어내도 본능적으로 끌리는 사이',
    shortLabel: '강한 끌림형',
    triggerKeywords: ['강한 끌림', '자극', '속도 차이', '감정 기복'],
    defaultBrightSide: '서로에게 없는 결을 건드려 처음부터 강하게 의식되는 끌림이 있습니다.',
    defaultShadowSide: '가까워질수록 표현 방식과 회복 속도 차이로 피로가 누적될 수 있어요.',
    defaultKeyAdvice: '싸운 직후 바로 결론내리지 말고, 감정이 가라앉은 뒤 다시 이야기하는 룰을 만들기.',
    fitTypes: ['dating', 'crush_or_something', 'reunion_or_breakup'],
    tone: 'sns-shareable-but-not-cheap',
  },
  {
    id: 'slow-burn-stability',
    title: '처음보다 시간이 지날수록 편해지는 사이',
    shortLabel: '천천히 스며드는 안정형',
    triggerKeywords: ['안정감', '오행 보완', '생활 리듬', '신뢰'],
    defaultBrightSide: '시간이 지날수록 서로의 결을 알게 되면서 편안함이 깊어지는 관계예요.',
    defaultShadowSide: '익숙해진 뒤 표현이 줄면, 한쪽이 외로움을 느낄 수 있습니다.',
    defaultKeyAdvice: '익숙함을 당연시하지 말고, 작은 인정·표현 루틴을 유지하기.',
    fitTypes: ['dating', 'married', 'friendship'],
    tone: 'warm',
  },
  {
    id: 'growth-through-conflict',
    title: '전생의 원수처럼 부딪히지만, 이번 생엔 성장 버튼일지도 모르는 사이',
    shortLabel: '성장 자극형',
    triggerKeywords: ['충돌', '자극', '성장', '반복 갈등'],
    defaultBrightSide: '실제로는 서로의 약한 부분을 건드려 성장 자극이 강한 관계라는 뜻이에요.',
    defaultShadowSide: '자극이 회복 룰 없이 반복되면 관계 자체가 지칠 수 있습니다.',
    defaultKeyAdvice: '갈등 뒤 회복 루틴을 미리 합의해두기 — 시간차·말투·확인 시점.',
    fitTypes: ['dating', 'married', 'coworker', 'reunion_or_breakup'],
    tone: 'playful',
  },
  {
    id: 'rule-needed-love',
    title: '마음은 있는데 룰이 없으면 쉽게 지치는 사이',
    shortLabel: '룰 필요형',
    triggerKeywords: ['끌림', '생활 차이', '책임', '회복 방식 차이'],
    defaultBrightSide: '서로 좋아하는 마음은 분명한 편이에요.',
    defaultShadowSide: '돈·책임·생활 리듬 같은 현실 룰이 없으면 빠르게 피로가 쌓입니다.',
    defaultKeyAdvice: '연락·약속·돈·집안일 등 작은 룰부터 글로 정리해두기.',
    fitTypes: ['dating', 'married'],
    tone: 'realistic',
  },
  {
    id: 'practical-partner',
    title: '감정보다 역할이 맞을 때 빛나는 사이',
    shortLabel: '파트너형',
    triggerKeywords: ['역할 분담', '성과', '책임', '현실감'],
    defaultBrightSide: '역할이 분명할 때 시너지가 가장 잘 나오는 관계예요.',
    defaultShadowSide: '역할이 흐려지거나 한쪽이 떠안으면 마찰이 쌓이기 쉽습니다.',
    defaultKeyAdvice: '결정 권한·성과 기준·금전 배분을 처음에 분명히 정하기.',
    fitTypes: ['coworker', 'married'],
    tone: 'practical',
  },
  {
    id: 'unforgettable-ambiguous',
    title: '애매할 때 가장 강하게 신경 쓰이는 사이',
    shortLabel: '썸 긴장형',
    triggerKeywords: ['호기심', '애매함', '속도 조절', '부담 포인트'],
    defaultBrightSide: '아직 정의되지 않은 상태가 오히려 끌림을 강하게 만드는 관계예요.',
    defaultShadowSide: '빠르게 밀어붙이거나 너무 길게 끌면 흐지부지될 위험이 있습니다.',
    defaultKeyAdvice: '연락·만남 빈도를 일정 페이스로 유지하되 부담 신호를 빠르게 읽기.',
    fitTypes: ['crush_or_something'],
    tone: 'sns-shareable',
  },
  {
    id: 'unfinished-emotion',
    title: '끝난 줄 알았는데 감정의 문이 완전히 닫히지 않는 사이',
    shortLabel: '미완의 감정형',
    triggerKeywords: ['미련', '반복 패턴', '재회 조건', '정리 필요'],
    defaultBrightSide: '두 사람의 감정이 단순히 식어서 멀어진 건 아닌 결을 가진 관계예요.',
    defaultShadowSide: '이전 갈등 패턴이 그대로 남아 있으면 다시 만나도 같은 이유로 지칠 수 있습니다.',
    defaultKeyAdvice: '재회 전에, 그때 반복됐던 문제를 다르게 다룰 수 있는지 먼저 확인하기.',
    fitTypes: ['reunion_or_breakup'],
    tone: 'careful',
  },
  {
    id: 'comfortable-friend-lover',
    title: '설렘보다 편안함으로 오래 가는 사이',
    shortLabel: '친구 같은 안정형',
    triggerKeywords: ['편안함', '동질감', '의리', '익숙함'],
    defaultBrightSide: '서로의 결이 비슷해 오래 함께 있어도 부담이 적은 관계예요.',
    defaultShadowSide: '익숙함이 당연해지면 설렘이 빨리 식어 권태로 이어질 수 있습니다.',
    defaultKeyAdvice: '한 달에 한 번이라도 평소와 다른 자리·환경에서 만나기.',
    fitTypes: ['dating', 'friendship', 'married'],
    tone: 'warm',
  },
  {
    id: 'missing-piece',
    title: '서로의 빈칸을 본능적으로 알아보는 사이',
    shortLabel: '보완형',
    triggerKeywords: ['오행 보완', '용신 보완', '균형', '안정감'],
    defaultBrightSide: '상대가 내게 부족한 결을 자연스럽게 채워주는 보완 구조예요.',
    defaultShadowSide: '한쪽이 일방적으로 채워주는 구조가 되면 피로가 쌓입니다.',
    defaultKeyAdvice: '서로가 채워주는 영역을 명확히 인식하고, 일방적 의존을 조심하기.',
    fitTypes: ['dating', 'married', 'friendship', 'coworker'],
    tone: 'premium',
  },
  {
    id: 'love-and-distance',
    title: '가까워지고 싶지만 적당한 거리가 필요한 사이',
    shortLabel: '거리 조절형',
    triggerKeywords: ['끌림', '거리감', '독립성', '피로 누적'],
    defaultBrightSide: '서로 독립적인 자기 영역을 존중할 때 더 매력적으로 보이는 관계예요.',
    defaultShadowSide: '너무 붙어 있으면 자기 페이스가 무너져 피로가 쌓일 수 있습니다.',
    defaultKeyAdvice: '주중 자기 시간·주말 함께 시간처럼 거리감 룰을 정하기.',
    fitTypes: ['dating', 'friendship', 'married'],
    tone: 'realistic',
  },
  {
    id: 'comfortable-but-flat',
    title: '편하지만 방심하면 설렘이 낮아지는 사이',
    shortLabel: '편안함 관리형',
    triggerKeywords: ['편안함', '익숙함', '설렘 저하', '루틴'],
    defaultBrightSide: '서로 큰 갈등 없이 편안하게 흐르는 관계예요.',
    defaultShadowSide: '루틴화되면 무관심처럼 느껴질 수 있고 한쪽이 외로울 수 있습니다.',
    defaultKeyAdvice: '서로 인정하는 말과 작은 변화 이벤트를 의식적으로 넣기.',
    fitTypes: ['dating', 'married', 'friendship'],
    tone: 'light',
  },
  {
    id: 'fire-and-brake',
    title: '한쪽은 불을 붙이고, 한쪽은 브레이크를 잡는 사이',
    shortLabel: '속도차 조율형',
    triggerKeywords: ['속도 차이', '표현 차이', '신중함', '직진'],
    defaultBrightSide: '한쪽의 추진력과 다른 쪽의 신중함이 균형을 만드는 결을 가진 관계예요.',
    defaultShadowSide: '속도·표현 차이가 큰 만큼 한쪽은 답답함, 다른 쪽은 부담을 느낄 수 있습니다.',
    defaultKeyAdvice: '결정의 페이스를 미리 공유하고 "잠깐 시간 두기" 신호를 약속하기.',
    fitTypes: ['dating', 'crush_or_something', 'coworker'],
    tone: 'sns-shareable',
  },
  {
    id: 'karma-comedy',
    title: '전생엔 티격태격했겠지만, 이번 생엔 서로의 과제일지도 모르는 사이',
    shortLabel: '티격태격 성장형',
    triggerKeywords: ['반복 충돌', '정서 자극', '성장', '관계 과제'],
    defaultBrightSide: '서로가 마주하기 싫었던 자기 모습을 비춰주는 결을 가진 관계예요.',
    defaultShadowSide: '회복 룰이 없으면 같은 자극이 반복되면서 지칠 수 있습니다.',
    defaultKeyAdvice: '감정이 격해질 때 멈춤 신호를 정하고, 같은 갈등을 두 번째 만나면 글로 정리하기.',
    fitTypes: ['dating', 'married', 'reunion_or_breakup', 'coworker'],
    tone: 'playful',
  },
];

export function findArchetypeById(id: string): ArchetypeCatalogEntry | undefined {
  return RELATIONSHIP_ARCHETYPE_CATALOG.find(a => a.id === id);
}
